### ISSUE TITLE
Minified CSS does not seem to match input

### ISSUE THREAD

**Issue by jawnsy** [redhat-rcue/rcue#72]
This might be a consequence of the way I'm building things (I'm manually replacing, e.g. `rcue/node_modules/patternfly` with a symlink to my local `patternfly`) - see #71

Here's code in my rcue-additions.css, built using patternfly master to include https://github.com/patternfly/patternfly/pull/624:

```css
.wizard-pf-steps-indicator .wizard-pf-step-number {
  background-color: #fff;
  border-radius: 50%;
  border: solid 2px #bbb;
  color: #bbb;
  font-size: 12px;
  font-weight: 700;
  height: 25px;
>>  left: calc(50% - 13px);
  line-height: 22px;
  position: absolute;
  top: 27px;
  width: 25px;
}
```

This is exactly what I want, and fixes the alignment issues identified. So far, so good. But using the built minified version, the problem reappears:

```css
.wizard-pf-steps-indicator .wizard-pf-step-number{background-color:#fff;border-radius:50%;border:2px solid #bbb;color:#bbb;font-size:12px;font-weight:700;height:25px;left:calc(37%);line-height:22px;position:absolute;top:27px;width:25px}
```

It takes a little horizontal scrolling to see it, but `left:calc(37%)` has reappeared from somewhere! I don't know if the minifier is doing this or if we're running the file through `less` twice, or something else?
